-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.asistente_evento
(
    id_asistente serial NOT NULL,
    codigo_evento character varying(20) COLLATE pg_catalog."default",
    run_asistente character varying(12) COLLATE pg_catalog."default",
    nombre_asistente character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT asistente_evento_pkey PRIMARY KEY (id_asistente)
);

CREATE TABLE IF NOT EXISTS public.cargo
(
    id_cargo serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cargo_pkey PRIMARY KEY (id_cargo)
);

CREATE TABLE IF NOT EXISTS public.comuna
(
    codigo_comuna integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    codigo_region integer NOT NULL,
    CONSTRAINT comuna_pkey PRIMARY KEY (codigo_comuna)
);

CREATE TABLE IF NOT EXISTS public.contacto_empresa
(
    id_contacto serial NOT NULL,
    rut_empresa character varying(15) COLLATE pg_catalog."default",
    run_persona character varying(12) COLLATE pg_catalog."default",
    nombre character varying(50) COLLATE pg_catalog."default",
    cargo character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT contacto_empresa_pkey PRIMARY KEY (id_contacto)
);

CREATE TABLE IF NOT EXISTS public.cuota
(
    id_cuota serial NOT NULL,
    id_membresia integer,
    mes integer NOT NULL,
    fecha_vencimiento date NOT NULL,
    monto_total integer NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cuota_pkey PRIMARY KEY (id_cuota)
);

CREATE TABLE IF NOT EXISTS public.empresa
(
    rut_empresa character varying(15) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT empresa_pkey PRIMARY KEY (rut_empresa)
);

CREATE TABLE IF NOT EXISTS public.evento
(
    codigo_evento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    fecha_evento date NOT NULL,
    codigo_lugar character varying(15) COLLATE pg_catalog."default",
    codigo_sucursal character varying(10) COLLATE pg_catalog."default",
    tipo_cliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    identificador_cliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT evento_pkey PRIMARY KEY (codigo_evento)
);

CREATE TABLE IF NOT EXISTS public.lugar
(
    codigo_lugar character varying(15) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    capacidad integer NOT NULL,
    codigo_sucursal character varying(10) COLLATE pg_catalog."default" NOT NULL,
    tipo_lugar character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT lugar_pkey PRIMARY KEY (codigo_lugar)
);

CREATE TABLE IF NOT EXISTS public.membresia
(
    id_socio serial not NULL,
    id_socio_titular integer,
    anio integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    monto_base integer NOT NULL,
    CONSTRAINT membresia_pkey PRIMARY KEY (id_socio)
);

CREATE TABLE IF NOT EXISTS public.naci
(
    run character varying(12) COLLATE pg_catalog."default",
    nac date
);

CREATE TABLE IF NOT EXISTS public.pago_cuota
(
    id_pago_cuota serial NOT NULL,
    cuota_numero integer,
    fecha_pago date NOT NULL,
    monto_pagado integer NOT NULL,
    medio_pago character varying(30) COLLATE pg_catalog."default",
    id_socio integer,
    CONSTRAINT pago_cuota_pkey PRIMARY KEY (id_pago_cuota)
);

CREATE TABLE IF NOT EXISTS public.pago_evento
(
    id_pago_evento serial NOT NULL,
    codigo_evento character varying(20) COLLATE pg_catalog."default",
    fecha_pago date NOT NULL,
    monto integer NOT NULL,
    tipo_pago character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pago_evento_pkey PRIMARY KEY (id_pago_evento)
);

CREATE TABLE IF NOT EXISTS public.pago_reserva
(
    id_pago_reserva serial NOT NULL,
    codigo_reserva character varying(20) COLLATE pg_catalog."default",
    fecha_pago date NOT NULL,
    monto integer NOT NULL,
    medio_pago character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT pago_reserva_pkey PRIMARY KEY (id_pago_reserva)
);

CREATE TABLE IF NOT EXISTS public.persona
(
    run character varying(12) COLLATE pg_catalog."default" NOT NULL,
    nombre_completo character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default",
    telefono_celular character varying(20) COLLATE pg_catalog."default",
    telefono_alternativo character varying(20) COLLATE pg_catalog."default",
    direccion_calle character varying(150) COLLATE pg_catalog."default",
    codigo_comuna integer,
    fecha_nacimiento date,
    CONSTRAINT persona_pkey PRIMARY KEY (run)
);

CREATE TABLE IF NOT EXISTS public.persona_cargo
(
    id_persona_cargo serial NOT NULL,
    run_persona character varying(12) COLLATE pg_catalog."default",
    id_cargo integer,
    codigo_sucursal character varying(10) COLLATE pg_catalog."default",
    fecha_inicio date NOT NULL,
    fecha_termino date,
    CONSTRAINT persona_cargo_pkey PRIMARY KEY (id_persona_cargo)
);

CREATE TABLE IF NOT EXISTS public.precio_lugar
(
    id_precio serial NOT NULL,
    codigo_lugar character varying(15) COLLATE pg_catalog."default",
    tipo_precio character varying(10) COLLATE pg_catalog."default" NOT NULL,
    dia_semana character varying(15) COLLATE pg_catalog."default",
    hora_inicio time without time zone,
    hora_termino time without time zone,
    fecha_inicio date,
    fecha_fin date,
    monto integer NOT NULL,
    CONSTRAINT precio_lugar_pkey PRIMARY KEY (id_precio)
);

CREATE TABLE IF NOT EXISTS public.region
(
    codigo_region integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT region_pkey PRIMARY KEY (codigo_region)
);

CREATE TABLE IF NOT EXISTS public.relacion_socio
(
    id_relacion serial NOT NULL,
    id_socio_titular integer,
    id_socio_dependiente integer,
    parentesco character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT relacion_socio_pkey PRIMARY KEY (id_relacion)
);

CREATE TABLE IF NOT EXISTS public.reserva
(
    codigo_reserva character varying(20) COLLATE pg_catalog."default" NOT NULL,
    codigo_lugar character varying(15) COLLATE pg_catalog."default",
    run_reservante character varying(12) COLLATE pg_catalog."default",
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT reserva_pkey PRIMARY KEY (codigo_reserva)
);

CREATE TABLE IF NOT EXISTS public.socio
(
    id_socio serial NOT NULL,
    run_persona character varying(12) COLLATE pg_catalog."default",
    tipo_socio character varying(30) COLLATE pg_catalog."default" NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    codigo_sucursal_base character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT socio_pkey PRIMARY KEY (id_socio)
);

CREATE TABLE IF NOT EXISTS public.sucursal
(
    codigo_sucursal character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(150) COLLATE pg_catalog."default" NOT NULL,
    codigo_comuna integer,
    CONSTRAINT sucursal_pkey PRIMARY KEY (codigo_sucursal)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario serial NOT NULL,
    run_persona character varying(12) COLLATE pg_catalog."default",
    email_login character varying(150) COLLATE pg_catalog."default" NOT NULL,
    clave_encriptada character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tipo_usuario character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS public.asistente_evento
    ADD CONSTRAINT asistente_evento_codigo_evento_fkey FOREIGN KEY (codigo_evento)
    REFERENCES public.evento (codigo_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comuna
    ADD CONSTRAINT comuna_codigo_region_fkey FOREIGN KEY (codigo_region)
    REFERENCES public.region (codigo_region) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.contacto_empresa
    ADD CONSTRAINT contacto_empresa_rut_empresa_fkey FOREIGN KEY (rut_empresa)
    REFERENCES public.empresa (rut_empresa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cuota
    ADD CONSTRAINT cuota_id_membresia_fkey FOREIGN KEY (id_membresia)
    REFERENCES public.membresia (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.evento
    ADD CONSTRAINT evento_codigo_lugar_fkey FOREIGN KEY (codigo_lugar)
    REFERENCES public.lugar (codigo_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.evento
    ADD CONSTRAINT evento_codigo_sucursal_fkey FOREIGN KEY (codigo_sucursal)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lugar
    ADD CONSTRAINT lugar_codigo_sucursal_fkey FOREIGN KEY (codigo_sucursal)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.membresia
    ADD CONSTRAINT membresia_id_socio_titular_fkey FOREIGN KEY (id_socio_titular)
    REFERENCES public.socio (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago_cuota
    ADD CONSTRAINT pago_cuota_id_cuota_fkey FOREIGN KEY (cuota_numero)
    REFERENCES public.cuota (id_cuota) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago_evento
    ADD CONSTRAINT pago_evento_codigo_evento_fkey FOREIGN KEY (codigo_evento)
    REFERENCES public.evento (codigo_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago_reserva
    ADD CONSTRAINT pago_reserva_codigo_reserva_fkey FOREIGN KEY (codigo_reserva)
    REFERENCES public.reserva (codigo_reserva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona
    ADD CONSTRAINT persona_codigo_comuna_fkey FOREIGN KEY (codigo_comuna)
    REFERENCES public.comuna (codigo_comuna) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona_cargo
    ADD CONSTRAINT persona_cargo_codigo_sucursal_fkey FOREIGN KEY (codigo_sucursal)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona_cargo
    ADD CONSTRAINT persona_cargo_id_cargo_fkey FOREIGN KEY (id_cargo)
    REFERENCES public.cargo (id_cargo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona_cargo
    ADD CONSTRAINT persona_cargo_run_persona_fkey FOREIGN KEY (run_persona)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.precio_lugar
    ADD CONSTRAINT precio_lugar_codigo_lugar_fkey FOREIGN KEY (codigo_lugar)
    REFERENCES public.lugar (codigo_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.relacion_socio
    ADD CONSTRAINT relacion_socio_id_socio_dependiente_fkey FOREIGN KEY (id_socio_dependiente)
    REFERENCES public.socio (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.relacion_socio
    ADD CONSTRAINT relacion_socio_id_socio_titular_fkey FOREIGN KEY (id_socio_titular)
    REFERENCES public.socio (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reserva
    ADD CONSTRAINT reserva_codigo_lugar_fkey FOREIGN KEY (codigo_lugar)
    REFERENCES public.lugar (codigo_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reserva
    ADD CONSTRAINT reserva_run_reservante_fkey FOREIGN KEY (run_reservante)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT socio_codigo_sucursal_base_fkey FOREIGN KEY (codigo_sucursal_base)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT socio_run_persona_fkey FOREIGN KEY (run_persona)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sucursal
    ADD CONSTRAINT sucursal_codigo_comuna_fkey FOREIGN KEY (codigo_comuna)
    REFERENCES public.comuna (codigo_comuna) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_run_persona_fkey FOREIGN KEY (run_persona)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;